/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import dao.CadastroFormularioDao;
import dao.CadastroPacienteDao;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;
import javax.swing.*;
import java.time.LocalDate;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.text.DateFormatter;
import javax.swing.text.DefaultFormatterFactory;
import model.CadastroFormularioModel;
import model.CadastroPacienteModel;

/**
 *
 * @author Maria Beatriz
 */
public class CadastroFormulario extends javax.swing.JFrame {

    /**
     * Creates new form CadastroFormulario
     */
    public CadastroFormulario() {
        initComponents();
    }

    public void setPatientData(String patientID, String patientName, Date patientBirthdate, String sexName) {
        jTPacienteID.setText(patientID);
        jTPacienteNome.setText(patientName);

        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        jFPacienteNascimento.setFormatterFactory(new DefaultFormatterFactory(new DateFormatter(dateFormat)));

        jFPacienteNascimento.setValue(patientBirthdate);

        jCPacienteSexo.setSelectedItem(sexName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        jLabel251 = new javax.swing.JLabel();
        jTFormularioID = new javax.swing.JTextField();
        jLabel252 = new javax.swing.JLabel();
        jFPacienteNascimento = new javax.swing.JFormattedTextField();
        jLabel253 = new javax.swing.JLabel();
        jTFormularioIdade = new javax.swing.JTextField();
        jLabel254 = new javax.swing.JLabel();
        jLabel255 = new javax.swing.JLabel();
        jCPacienteSexo = new javax.swing.JComboBox<>();
        jLabel256 = new javax.swing.JLabel();
        jTPacienteID = new javax.swing.JTextField();
        jLabel257 = new javax.swing.JLabel();
        jTPacienteNome = new javax.swing.JTextField();
        jSeparator31 = new javax.swing.JSeparator();
        jLabel258 = new javax.swing.JLabel();
        jTFormularioAltura = new javax.swing.JTextField();
        jLabel259 = new javax.swing.JLabel();
        jLabel260 = new javax.swing.JLabel();
        jTFormularioPeso = new javax.swing.JTextField();
        jLabel261 = new javax.swing.JLabel();
        jLabel262 = new javax.swing.JLabel();
        jTFormularioIMC = new javax.swing.JTextField();
        jLabel263 = new javax.swing.JLabel();
        jTFormularioPescoco = new javax.swing.JTextField();
        jLabel264 = new javax.swing.JLabel();
        jLabel265 = new javax.swing.JLabel();
        jTFormularioCintura = new javax.swing.JTextField();
        jLabel266 = new javax.swing.JLabel();
        jLabel267 = new javax.swing.JLabel();
        jTFormularioObjetivo = new javax.swing.JTextField();
        jSeparator32 = new javax.swing.JSeparator();
        jLabel268 = new javax.swing.JLabel();
        jScrollPane71 = new javax.swing.JScrollPane();
        jTAFormularioExercicio = new javax.swing.JTextArea();
        jLabel269 = new javax.swing.JLabel();
        jScrollPane72 = new javax.swing.JScrollPane();
        jTAFormularioHabito = new javax.swing.JTextArea();
        jLabel270 = new javax.swing.JLabel();
        jFFormularioDtExame = new javax.swing.JFormattedTextField();
        jScrollPane73 = new javax.swing.JScrollPane();
        jTAFormularioAlimentacao = new javax.swing.JTextArea();
        jLabel271 = new javax.swing.JLabel();
        jSeparator33 = new javax.swing.JSeparator();
        jLabel272 = new javax.swing.JLabel();
        jScrollPane74 = new javax.swing.JScrollPane();
        jTAFormularioSintoma = new javax.swing.JTextArea();
        jScrollPane75 = new javax.swing.JScrollPane();
        jTAFormularioUrina = new javax.swing.JTextArea();
        jLabel273 = new javax.swing.JLabel();
        jScrollPane76 = new javax.swing.JScrollPane();
        jTAFormularioFezes = new javax.swing.JTextArea();
        jLabel274 = new javax.swing.JLabel();
        jScrollPane77 = new javax.swing.JScrollPane();
        jTAFormularioObservacao = new javax.swing.JTextArea();
        jLabel275 = new javax.swing.JLabel();
        jBFormularioConcluir = new javax.swing.JButton();
        jBFormularioInvalidar = new javax.swing.JButton();
        jBFormularioSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel251.setText("ID Formulário");

        jTFormularioID.setEditable(false);

        jLabel252.setText("Nascimento");

        jFPacienteNascimento.setEditable(false);
        try {
            jFPacienteNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFPacienteNascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFPacienteNascimentoFocusLost(evt);
            }
        });

        jLabel253.setText("Idade");

        jTFormularioIdade.setEditable(false);

        jLabel254.setText("Anos");

        jLabel255.setText("Sexo");

        jCPacienteSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "Intersexo" }));
        jCPacienteSexo.setSelectedIndex(-1);

        jLabel256.setText("ID paciente");

        jTPacienteID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTPacienteIDFocusLost(evt);
            }
        });
        jTPacienteID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTPacienteIDMouseClicked(evt);
            }
        });

        jLabel257.setText("Nome");

        jTPacienteNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTPacienteNomeFocusLost(evt);
            }
        });

        jLabel258.setText("Altura");

        jTFormularioAltura.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFormularioAlturaFocusLost(evt);
            }
        });

        jLabel259.setText("Metros");

        jLabel260.setText("Peso");

        jTFormularioPeso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFormularioPesoFocusLost(evt);
            }
        });

        jLabel261.setText("Kg");

        jLabel262.setText("IMC");

        jTFormularioIMC.setEditable(false);

        jLabel263.setText("Largura do Pescoço");

        jLabel264.setText(" Cm");

        jLabel265.setText("Largura da Cintura");

        jLabel266.setText(" Cm");

        jLabel267.setText("Objetivo");

        jLabel268.setText("Hábitos");

        jScrollPane71.setHorizontalScrollBar(null);

        jTAFormularioExercicio.setColumns(20);
        jTAFormularioExercicio.setRows(5);
        jScrollPane71.setViewportView(jTAFormularioExercicio);

        jLabel269.setText("Exercícios");

        jScrollPane72.setHorizontalScrollBar(null);

        jTAFormularioHabito.setColumns(20);
        jTAFormularioHabito.setRows(5);
        jScrollPane72.setViewportView(jTAFormularioHabito);

        jLabel270.setText("Data do Exame");

        jFFormularioDtExame.setEditable(false);
        try {
            jFFormularioDtExame.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jScrollPane73.setHorizontalScrollBar(null);

        jTAFormularioAlimentacao.setColumns(20);
        jTAFormularioAlimentacao.setRows(5);
        jScrollPane73.setViewportView(jTAFormularioAlimentacao);

        jLabel271.setText("Alimentação");

        jLabel272.setText("Sintomas");

        jScrollPane74.setHorizontalScrollBar(null);

        jTAFormularioSintoma.setColumns(20);
        jTAFormularioSintoma.setRows(5);
        jScrollPane74.setViewportView(jTAFormularioSintoma);

        jScrollPane75.setHorizontalScrollBar(null);

        jTAFormularioUrina.setColumns(20);
        jTAFormularioUrina.setRows(5);
        jScrollPane75.setViewportView(jTAFormularioUrina);

        jLabel273.setText("Urina");

        jScrollPane76.setHorizontalScrollBar(null);

        jTAFormularioFezes.setColumns(20);
        jTAFormularioFezes.setRows(5);
        jScrollPane76.setViewportView(jTAFormularioFezes);

        jLabel274.setText("Fezes");

        jScrollPane77.setHorizontalScrollBar(null);

        jTAFormularioObservacao.setColumns(20);
        jTAFormularioObservacao.setRows(5);
        jScrollPane77.setViewportView(jTAFormularioObservacao);

        jLabel275.setText("Observações");

        jBFormularioConcluir.setText("Concluir");
        jBFormularioConcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBFormularioConcluirMouseClicked(evt);
            }
        });

        jBFormularioInvalidar.setText("Invalidar");
        jBFormularioInvalidar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBFormularioInvalidarMouseClicked(evt);
            }
        });

        jBFormularioSalvar.setText("Salvar");
        jBFormularioSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBFormularioSalvarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator32)
            .addComponent(jSeparator31)
            .addComponent(jSeparator33)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFormularioID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel251))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel270)
                                    .addComponent(jFFormularioDtExame, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel256)
                                    .addComponent(jTPacienteID, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel257)
                                    .addComponent(jTPacienteNome, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFPacienteNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel252))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel253, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTFormularioIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .addGap(3, 3, 3)
                                .addComponent(jLabel254)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel255)
                                    .addComponent(jCPacienteSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel258)
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addComponent(jTFormularioAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel259)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel260)
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addComponent(jTFormularioPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel261)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel262)
                                    .addComponent(jTFormularioIMC, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel11Layout.createSequentialGroup()
                                        .addComponent(jTFormularioPescoco, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel264))
                                    .addComponent(jLabel263, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addComponent(jTFormularioCintura, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel266))
                                    .addComponent(jLabel265)))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel267)
                                    .addComponent(jTFormularioObjetivo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel268)
                                    .addComponent(jScrollPane72, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel269)
                                    .addComponent(jScrollPane71, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel271)
                                    .addComponent(jScrollPane73, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jScrollPane74, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane75, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel272)
                                .addGap(203, 203, 203)
                                .addComponent(jLabel273))
                            .addComponent(jLabel275)
                            .addComponent(jScrollPane77))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel274)
                            .addComponent(jScrollPane76, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jBFormularioInvalidar)
                .addGap(162, 162, 162)
                .addComponent(jBFormularioSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBFormularioConcluir)
                .addGap(131, 131, 131))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel270)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFFormularioDtExame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel251)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFormularioID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel256)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTPacienteID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel257)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTPacienteNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel252)
                    .addComponent(jLabel253)
                    .addComponent(jLabel255))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFPacienteNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFormularioIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel254)
                    .addComponent(jCPacienteSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jSeparator31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel262)
                                    .addComponent(jLabel258)
                                    .addComponent(jLabel260, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTFormularioPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFormularioAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel261)
                                    .addComponent(jTFormularioIMC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel259)))
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel11Layout.createSequentialGroup()
                                    .addComponent(jLabel263)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTFormularioPescoco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel264)))
                                .addGroup(jPanel11Layout.createSequentialGroup()
                                    .addComponent(jLabel265)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTFormularioCintura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel266)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel267)
                            .addComponent(jLabel268))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFormularioObjetivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane72, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel269)
                            .addComponent(jLabel271))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane71, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane73, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel273)
                            .addComponent(jLabel274))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane76, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane75, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel272)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane74, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addComponent(jLabel275)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane77, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBFormularioConcluir)
                    .addComponent(jBFormularioInvalidar)
                    .addComponent(jBFormularioSalvar))
                .addGap(616, 616, 616))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calcularIMC() {
        try {
            String alturaText = jTFormularioAltura.getText().replaceAll("[\\ ]", "").trim();
            String pesoText = jTFormularioPeso.getText().replaceAll("[\\ ]", "").trim();
            if (!pesoText.isEmpty() && !alturaText.isEmpty()) {
                pesoText = jTFormularioPeso.getText().replace(",", ".").trim();
                alturaText = jTFormularioAltura.getText().replace(",", ".").trim();
                double peso = Double.parseDouble(pesoText);
                double altura = Double.parseDouble(alturaText);

                double imc = peso / (altura * altura);

                String classificacao;
                if (imc <= 16.9) {
                    classificacao = "Muito abaixo do peso";
                } else if (imc >= 17 && imc <= 18.4) {
                    classificacao = "Abaixo do peso";
                } else if (imc >= 18.5 && imc <= 24.9) {
                    classificacao = "Normal";
                } else if (imc >= 25 && imc <= 29.9) {
                    classificacao = "Acima do peso";
                } else if (imc >= 30 && imc <= 34.9) {
                    classificacao = "Obesidade I";
                } else if (imc >= 35 && imc <= 40) {
                    classificacao = "Obesidade II";
                } else {
                    classificacao = "Obesidade III";
                }

                jTFormularioIMC.setText(classificacao);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro!");
        }
    }

    private void jTFormularioAlturaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFormularioAlturaFocusLost
        calcularIMC();
    }//GEN-LAST:event_jTFormularioAlturaFocusLost

    private void jTFormularioPesoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFormularioPesoFocusLost
        calcularIMC();
    }//GEN-LAST:event_jTFormularioPesoFocusLost


    private void jBFormularioConcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBFormularioConcluirMouseClicked
        try {
            CadastroFormularioDao cadastroDao = new CadastroFormularioDao();
            ArrayList<CadastroFormularioModel> listaCadastros = cadastroDao.consultar();
            int linha = -1;
            String formID = jTFormularioID.getText();
            for (int i = 0; i < listaCadastros.size(); i++) {
                CadastroFormularioModel cadastro = listaCadastros.get(i);
                if (formID.equals(String.valueOf(cadastro.getFormID()))) {
                    linha = i;
                    break;
                }
            }

            CadastroFormularioModel cadastroSelecionado = listaCadastros.get(linha);
            String status = cadastroSelecionado.getFormStatusName();

            if ("Em andamento".equals(status)) {
                cadastroSelecionado.setFormStatusName("Concluido");
                cadastroDao.alterar(cadastroSelecionado);
                JOptionPane.showMessageDialog(null, "Formulário concluido com sucesso.");
            } else {
                JOptionPane.showMessageDialog(null, "Exame concluido ou cancelado");
            }

            this.dispose();
            Tabelas tabelas = new Tabelas();
            tabelas.atualizaTabelaForm(listaCadastros);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao invalidar o formulário:\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBFormularioConcluirMouseClicked

    private void jBFormularioInvalidarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBFormularioInvalidarMouseClicked
        try {
            CadastroFormularioDao cadastroDao = new CadastroFormularioDao();
            ArrayList<CadastroFormularioModel> listaCadastros = cadastroDao.consultar();
            int linha = -1;
            String formID = jTFormularioID.getText();
            for (int i = 0; i < listaCadastros.size(); i++) {
                CadastroFormularioModel cadastro = listaCadastros.get(i);
                if (formID.equals(String.valueOf(cadastro.getFormID()))) {
                    linha = i;
                    break;
                }
            }

            CadastroFormularioModel cadastroSelecionado = listaCadastros.get(linha);
            String status = cadastroSelecionado.getFormStatusName();

            if ("Concluido".equals(status)) {
                cadastroSelecionado.setFormStatusName("Em andamento");
                cadastroDao.alterar(cadastroSelecionado);
                JOptionPane.showMessageDialog(null, "Formulário invalidado com sucesso.");
            } else {
                JOptionPane.showMessageDialog(null, "Exame em andamento ou cancelado");
            }
            this.dispose();
            Tabelas tabelas = new Tabelas();
            tabelas.atualizaTabelaForm(listaCadastros);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao invalidar o formulário:\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBFormularioInvalidarMouseClicked

    private void jBFormularioSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBFormularioSalvarMouseClicked
        try {
            CadastroFormularioDao cadastroDao = new CadastroFormularioDao();
            ArrayList<CadastroFormularioModel> listaCadastros = cadastroDao.consultar();
            int linha = -1;
            String formID = jTFormularioID.getText();

            int i;
            for (i = 0; i < listaCadastros.size(); i++) {
                CadastroFormularioModel cadastro = listaCadastros.get(i);
                if (formID.equals(String.valueOf(cadastro.getFormID()))) {
                    linha = i;
                    break;
                }
            }

            CadastroFormularioModel cadastroSelecionado;
            if (linha == -1) {
                cadastroSelecionado = new CadastroFormularioModel();
                int novoID = listaCadastros.stream()
                        .mapToInt(CadastroFormularioModel::getFormID)
                        .max()
                        .orElse(0) + 1;
                cadastroSelecionado.setFormID(novoID);
                cadastroSelecionado.setFormStatusName("Em andamento");
            } else {
                cadastroSelecionado = listaCadastros.get(linha);
            }

            cadastroSelecionado.setPatientID(Integer.parseInt(jTPacienteID.getText()));
            cadastroSelecionado.setPatientName(jTPacienteNome.getText());

            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            java.util.Date utilDateExame = dateFormat.parse(jFFormularioDtExame.getText());
            java.util.Date utilDateNascimento = dateFormat.parse(jFPacienteNascimento.getText());

            java.sql.Date sqlDateExame = new java.sql.Date(utilDateExame.getTime());
            java.sql.Date sqlDateNascimento = new java.sql.Date(utilDateNascimento.getTime());

            cadastroSelecionado.setFormExamDate(sqlDateExame);
            cadastroSelecionado.setPatientBirthdate(sqlDateNascimento);
            
            cadastroSelecionado.setSexName((String) jCPacienteSexo.getSelectedItem());
            cadastroSelecionado.setFormHeight(Double.parseDouble(jTFormularioAltura.getText()));
            cadastroSelecionado.setFormWeight(Double.parseDouble(jTFormularioPeso.getText()));
            cadastroSelecionado.setImcName(jTFormularioIMC.getText());
            cadastroSelecionado.setFormNeckWidth(Double.parseDouble(jTFormularioPescoco.getText()));
            cadastroSelecionado.setFormWaistWidth(Double.parseDouble(jTFormularioCintura.getText()));
            cadastroSelecionado.setFormObjective(jTFormularioObjetivo.getText());
            cadastroSelecionado.setFormHabits(jTAFormularioHabito.getText());
            cadastroSelecionado.setFormExercises(jTAFormularioExercicio.getText());
            cadastroSelecionado.setFormFeedingPattern(jTAFormularioAlimentacao.getText());
            cadastroSelecionado.setFormSintoms(jTAFormularioSintoma.getText());
            cadastroSelecionado.setFormUrine(jTAFormularioUrina.getText());
            cadastroSelecionado.setFormFeces(jTAFormularioFezes.getText());
            cadastroSelecionado.setFormObservation(jTAFormularioObservacao.getText());

            if (linha == -1) {
                cadastroDao.inserir(cadastroSelecionado);
                JOptionPane.showMessageDialog(null, "Novo formulário criado com sucesso.");
            } else if ("Em andamento".equals(cadastroSelecionado.getFormStatusName())) {
                cadastroDao.alterar(cadastroSelecionado);
                JOptionPane.showMessageDialog(null, "Formulário atualizado com sucesso.");
            } else {
                JOptionPane.showMessageDialog(null, "Somente formulários com status 'Em andamento' podem ser alterados.");
                return;
            }

            Tabelas tabelas = new Tabelas();
            tabelas.atualizaTabelaForm(cadastroDao.consultar());

            cadastroDao.vincularFormPaciente(cadastroSelecionado);

            this.dispose();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao salvar o formulário:\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBFormularioSalvarMouseClicked

    private void jFPacienteNascimentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFPacienteNascimentoFocusLost
        calcularIdade();
    }//GEN-LAST:event_jFPacienteNascimentoFocusLost

    private void jTPacienteIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTPacienteIDMouseClicked
        if (evt.getClickCount() == 2 && evt.getButton() == MouseEvent.BUTTON1) {
            new Thread() {
                @Override
                public void run() {
                    try {
                        PesquisaPaciente pesquisaPaciente = new PesquisaPaciente(CadastroFormulario.this);
                        pesquisaPaciente.setVisible(true);
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, "Ocorreu um erro inesperado:\n" + ex.getMessage(), "ERRO!", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }.start();
        }
    }//GEN-LAST:event_jTPacienteIDMouseClicked

    private void jTPacienteNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTPacienteNomeFocusLost
        new Thread() {
            @Override
            public void run() {
                try {
                    CadastroPacienteDao cadastroDao = new CadastroPacienteDao();
                    ArrayList<CadastroPacienteModel> listaCadastros = cadastroDao.consultar();
                    int linha = -1;
                    String PacienteNome = jTPacienteNome.getText().trim();

                    for (int i = 0; i < listaCadastros.size(); i++) {
                        CadastroPacienteModel cadastro = listaCadastros.get(i);
                        if (PacienteNome.equalsIgnoreCase(cadastro.getPatientName())) {
                            linha = i;
                            break;
                        }
                    }

                    if (linha != -1) {
                        CadastroPacienteModel cadastroSelecionado = listaCadastros.get(linha);

                        jTPacienteID.setText(String.valueOf(cadastroSelecionado.getPatientID()));
                    } else {
                        JOptionPane.showMessageDialog(null, "Paciente não encontrado.", "Informação", JOptionPane.INFORMATION_MESSAGE);
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Ocorreu um erro inesperado:\n" + ex.getMessage(), "ERRO!", JOptionPane.ERROR_MESSAGE);
                }
            }
        }.start();
    }//GEN-LAST:event_jTPacienteNomeFocusLost

    private void jTPacienteIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTPacienteIDFocusLost
        new Thread(() -> {
            try {
                CadastroPacienteDao cadastroDao = new CadastroPacienteDao();
                ArrayList<CadastroPacienteModel> listaCadastros = cadastroDao.consultar();
                int linha = -1;
                String pacienteID = jTPacienteID.getText().trim();

                for (int i = 0; i < listaCadastros.size(); i++) {
                    CadastroPacienteModel cadastro = listaCadastros.get(i);
                    if (pacienteID.equals(String.valueOf(cadastro.getPatientID()))) {
                        linha = i;
                        break;
                    }
                }

                if (linha != -1) {
                    CadastroPacienteModel cadastroSelecionado = listaCadastros.get(linha);

                    jTPacienteNome.setText(cadastroSelecionado.getPatientName());
                    jCPacienteSexo.setSelectedItem(cadastroSelecionado.getSexName());
                    Date patientBirthdate = cadastroSelecionado.getPatientBirthdate();
                    SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
                    jFPacienteNascimento.setText(dateFormat.format(patientBirthdate));

                    calcularIdade();

                } else {
                    JOptionPane.showMessageDialog(null, "Paciente não encontrado.", "Informação", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Ocorreu um erro inesperado:\n" + ex.getMessage(), "ERRO!", JOptionPane.ERROR_MESSAGE);
            }
        }).start();
    }//GEN-LAST:event_jTPacienteIDFocusLost

    public void calcularIdade() {
        try {
            String dtNascimentoText = jFPacienteNascimento.getText().replaceAll("[\\ ]", "").trim();
            dtNascimentoText = jFPacienteNascimento.getText();

            if (!dtNascimentoText.isEmpty()) {
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

                LocalDate dtNascimento = LocalDate.parse(dtNascimentoText, formatter);

                LocalDate currentDate = LocalDate.now();

                Period period = Period.between(dtNascimento, currentDate);

                int idade = period.getYears();
                String idadeString;
                idadeString = String.valueOf(idade);

                jTFormularioIdade.setText(idadeString);
            } else {
                JOptionPane.showMessageDialog(null, "Data de nascimento está vazia!");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro: " + ex.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFormulario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFormulario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFormulario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFormulario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFormulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBFormularioConcluir;
    private javax.swing.JButton jBFormularioInvalidar;
    private javax.swing.JButton jBFormularioSalvar;
    public javax.swing.JComboBox<String> jCPacienteSexo;
    public javax.swing.JFormattedTextField jFFormularioDtExame;
    public javax.swing.JFormattedTextField jFPacienteNascimento;
    private javax.swing.JLabel jLabel251;
    private javax.swing.JLabel jLabel252;
    private javax.swing.JLabel jLabel253;
    private javax.swing.JLabel jLabel254;
    private javax.swing.JLabel jLabel255;
    private javax.swing.JLabel jLabel256;
    private javax.swing.JLabel jLabel257;
    private javax.swing.JLabel jLabel258;
    private javax.swing.JLabel jLabel259;
    private javax.swing.JLabel jLabel260;
    private javax.swing.JLabel jLabel261;
    private javax.swing.JLabel jLabel262;
    private javax.swing.JLabel jLabel263;
    private javax.swing.JLabel jLabel264;
    private javax.swing.JLabel jLabel265;
    private javax.swing.JLabel jLabel266;
    private javax.swing.JLabel jLabel267;
    private javax.swing.JLabel jLabel268;
    private javax.swing.JLabel jLabel269;
    private javax.swing.JLabel jLabel270;
    private javax.swing.JLabel jLabel271;
    private javax.swing.JLabel jLabel272;
    private javax.swing.JLabel jLabel273;
    private javax.swing.JLabel jLabel274;
    private javax.swing.JLabel jLabel275;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JScrollPane jScrollPane71;
    private javax.swing.JScrollPane jScrollPane72;
    private javax.swing.JScrollPane jScrollPane73;
    private javax.swing.JScrollPane jScrollPane74;
    private javax.swing.JScrollPane jScrollPane75;
    private javax.swing.JScrollPane jScrollPane76;
    private javax.swing.JScrollPane jScrollPane77;
    private javax.swing.JSeparator jSeparator31;
    private javax.swing.JSeparator jSeparator32;
    private javax.swing.JSeparator jSeparator33;
    public javax.swing.JTextArea jTAFormularioAlimentacao;
    public javax.swing.JTextArea jTAFormularioExercicio;
    public javax.swing.JTextArea jTAFormularioFezes;
    public javax.swing.JTextArea jTAFormularioHabito;
    public javax.swing.JTextArea jTAFormularioObservacao;
    public javax.swing.JTextArea jTAFormularioSintoma;
    public javax.swing.JTextArea jTAFormularioUrina;
    public javax.swing.JTextField jTFormularioAltura;
    public javax.swing.JTextField jTFormularioCintura;
    public javax.swing.JTextField jTFormularioID;
    public javax.swing.JTextField jTFormularioIMC;
    public javax.swing.JTextField jTFormularioIdade;
    public javax.swing.JTextField jTFormularioObjetivo;
    public javax.swing.JTextField jTFormularioPescoco;
    public javax.swing.JTextField jTFormularioPeso;
    public javax.swing.JTextField jTPacienteID;
    public javax.swing.JTextField jTPacienteNome;
    // End of variables declaration//GEN-END:variables
}
